config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  get '/signout', to: 'sessions#destroy'

  get '/legislators', to: 'members#profile'
  post '/legislators', to: 'favorites#create'

  resources :sessions, only: [:create]
  resources :users
  resources :members

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :favorites
  has_many :users, through: :favorites
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :favorites

  before_create :create_remember_token
  before_save :normalize_fields

  # Validate name:
  validates :name,
    presence: true,
    length: { maximum: 50 }

  # Validate email address:
  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  # Validate password length:
  validates :password,
    length: { minimum: 8 }

  # Secure password features:
  has_secure_password

  # Create a new remember token for a user:
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  # Hash a token
  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  # Creates a new session token for the user:
  def create_remember_token
    remember_token = User.hash(User.new_remember_token)
  end

  # Normalize fields for consistency:
  def normalize_fields
    self.email.downcase!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include TweetsHelper

end

app/controllers/congress_controller.rb
class CongressController < ApplicationController

  def index
    response = HTTParty.get("https://congress.api.sunlightfoundation.com/legislators?apikey=0a104545f05a41bd9c7a93574c768e78&per_page=all")
    @results = response['results']
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
  end

  def create
    if current_user
      current_user.favorites.create(favorite_params)
      redirect_to current_user
    else
      redirect_to root_path
    end
  end

  private

    def favorite_params
      params.require(:favorite).permit(:member_id, :user_id)
    end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :find_member, only: [:show]

  def index
    response = HTTParty.get("https://congress.api.sunlightfoundation.com/legislators?apikey=0a104545f05a41bd9c7a93574c768e78&per_page=all")
    @results = response['results']
  end

  def show
    @tweets = get_tweets('adampbarrett')
    render :show
  end

  def profile
    response = HTTParty.get("https://congress.api.sunlightfoundation.com/legislators?apikey=0a104545f05a41bd9c7a93574c768e78&bioguide_id=#{params[:id]}")
    @results = response['results']
    @twitter_id = @results[0]['twitter_id']
    @tweets = get_tweets(@twitter_id)
  end

  def create
    @member = Member.create(params[:id])
    redirect_to @member
  end


  private

  def find_member
    @member = Member.find(params[:bioguide_id])
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # Find the user by email:
    user = User.find_by(email: params[:session][:email].downcase)

    # Test if the user was found AND authenticates
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or root_url
    else
      flash[:error] = 'Invalid email/password'
      redirect_to signin_path
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to @user
      else
        render :new
    end
  end

  def show
    @favorites = @user.favorites
    response = HTTParty.get("https://congress.api.sunlightfoundation.com/legislators?apikey=0a104545f05a41bd9c7a93574c768e78&bioguide_id=#{params[:favorites]}")
    @results = response['results']
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  Congress.key = "0a104545f05a41bd9c7a93574c768e78"

end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Current User methods:

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    current_user == user
  end

  # Signin Status methods:

  def signed_in?
    !current_user.nil?
  end

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  # Location Management methods:

  def store_location
    if request.get?
      session[:return_to] = request.url
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  # Security Checkpoint method:

  def require_signin
    unless signed_in?
      store_location
      flash[:error] = 'Please sign in.'
      redirect_to signin_url
    end
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper

  def get_tweets(handle)
    require 'twitter'

    @client = Twitter::REST::Client.new do |config|
      config.consumer_key       = 'HFJtymOEjQ6mc9FASGDXyp2KS'
      config.consumer_secret    = 'wZAVQLDSIVyoiogZn1owCIs0inuryp6whAtl6BdzTHcaQx4f93'
      config.access_token        = '300381691-gTe1rOB3UxjtaaP0WBoACcIUXj5mt2czfguX0KrB'
      config.access_token_secret = 'Kgp4Z4iojtjXiEQO6n1toHVHtKMS9D44SowfkAJDjL7le'
    end

    return @client.user_timeline(handle)
  end

end

app/views/common/_signout.html.erb
<% if signed_in? %>

  <%= form_for :session, url: signout_path, method: 'delete' do |f| %>
    Signed in as <%= link_to current_user.name, current_user %>
    <%= f.submit "Sign out", id: 'signout', class: 'session-btn' %>
  <% end %>

<% else %>

  <%= link_to "Sign In", signin_path, class: 'session-btn' %>
  <%= link_to "Sign up", signup_path, class: 'session-btn' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CongressionalIo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>


<%= render 'refills/navigation' %>


<%= yield %>

<%= render 'refills/footer' %>

</body>
</html>

app/views/members/index.html.erb
<h2>Members of Congress</h2>

  <% @results.each do |result| %>
    <li><%= link_to "#{result['first_name']} #{result['last_name']}", "/legislators?id=#{result['bioguide_id']}" %> | <%= result["twitter_id"] %></li>
  <% end %>

app/views/members/profile.html.erb
<h2><%= @results[0]['first_name'] %>
<%= @results[0]['last_name'] %></h2>

<% if signed_in? %>

  <%= form_tag "/legislators" do %>
    <%= hidden_field "favorite", "member_id", :value => @results[0]["bioguide_id"] %>
    <%= hidden_field "favorite", "user_id", :value => current_user.id %>
    <%= submit_tag 'Favorite' %>
  <% end %>

<% end %>

<p>Party: <%= @results[0]['party'] %></p>
<p>Twitter ID: <a href="http://twitter.com/<%= @results[0]['twitter_id'] %>" target="_blank"><%= @results[0]['twitter_id'] %></a></p>

<h2>Tweets</h2>
<% @tweets.each do |tweet| %>
  <li><%= tweet.text %></li>
<% end %>

app/views/members/show.html.erb
hello world

<% @tweets.each do |tweet| %>
  <h1><%= tweet.text %></h1>
<% end %>

app/views/members/test.html.erb
test123

app/views/refills/_footer.html.erb
<footer class="footer">
  <div class="footer-logo">
    <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt="">
  </div>
  <div class="footer-links">
    <ul>
      <li><h3>Content</h3></li>
      <li><a href="javascript:void(0)">About</a></li>
      <li><a href="javascript:void(0)">Contact</a></li>
      <li><a href="javascript:void(0)">Products</a></li>
    </ul>
    <ul>
      <li><h3>Follow Us</h3></li>
      <li><a href="javascript:void(0)">Facebook</a></li>
      <li><a href="javascript:void(0)">Twitter</a></li>
      <li><a href="javascript:void(0)">YouTube</a></li>
    </ul>
    <ul>
      <li><h3>Legal</h3></li>
      <li><a href="javascript:void(0)">Terms and Conditions</a></li>
      <li><a href="javascript:void(0)">Privacy Policy</a></li>
    </ul>
  </div>

  <hr>

  <p>Disclaimer area lorem ipsum dolor sit amet, consectetur adipisicing elit. Rerum, nostrum repudiandae saepe.</p>
</footer>

app/views/refills/_hero.html.erb
<div class="hero">
	<div class="hero-inner">
    <a href="" class="hero-logo"><img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt=""></a>
		<div class="hero-copy">
			<h1>Welcome to a Congressional Twitter App</h1>
			<p>Check out different legislator profile pages and add to your favorites.</p>
		</div>
    <a href="/members"><button>View Members of Congress</button></a>
	</div>
</div>

app/views/refills/_navigation.html.erb
<header class="navigation">
  <div class="menu-wrapper">
    <a href="javascript:void(0)" class="logo">
      <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt="">
    </a>
    <p class="navigation-menu-button" id="js-mobile-menu">MENU</p>
    <div class="nav">
      <ul id="navigation-menu">
        <li class="nav-link"><a href="/">Home</a></li>
        <li class="nav-link"><a href="/members">Members</a></li>
        <li class="nav-link"><a href="/users">Users</a></li>
      </ul>
    </div>
    <div class="navigation-tools">
      <div class="search-bar">
        <div class="search-and-submit">
          <input type="search" placeholder="Enter Search" />
          <button type="submit">
            <img src="https://raw.githubusercontent.com/Magnus-G/Random/master/search-icon.png" alt="">
          </button>
        </div>
      </div>
      <%= render 'common/signout' %>
    </div>
  </div>
</header>

<script>
  $(function() {
    var menu = $('#navigation-menu');
    var menuToggle = $('#js-mobile-menu');
    var signUp = $('.sign-up');

    $(menuToggle).on('click', function(e) {
      e.preventDefault();
      menu.slideToggle(function(){
        if(menu.is(':hidden')) {
          menu.removeAttr('style');
        }
      });
    });

    // underline under the active nav item
    $(".nav .nav-link").click(function() {
      $(".nav .nav-link").each(function() {
        $(this).removeClass("active-nav-item");
      });
      $(this).addClass("active-nav-item");
      $(".nav .more").removeClass("active-nav-item");
    });
  });
</script>

app/views/users/_user_form.html.erb
 <% if @user.errors.any? %>
 <b>Errors:</b>
 <ul>
   <% @user.errors.full_messages.each do |msg| %>
   <li><%= msg %></li>
   <% end %>
 </ul>
 <% end %>

 <%= form_for @user do |f| %>
   <%= f.label :name %>
   <%= f.text_field :name %>

   <%= f.label :email %>
   <%= f.text_field :email %>

   <%= f.label :password %>
   <%= f.password_field :password %>

   <%= f.label :password_confirmation, 'Confirm Password' %>
   <%= f.password_field :password_confirmation %>

   <%= f.submit 'Submit', id: 'submit' %>
 <% end %>

app/views/users/edit.html.erb
<h1>Edit <%= @user.name %></h1>
<%= render "user_form" %>

<hr>

<%= form_for @user, method: 'delete' do |f| %>
  <%= f.submit "Delete" %>
<% end %>

<hr>

<%= link_to "Cancel", @user %>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
<% @users.each do |user| %>
  <li><%= link_to user.name, user %>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>Create a User</h1>
<%= render "user_form" %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<%= @user.email %>

<h2>Favorite Members of Congress</h2><hr>

<ul>
  <% @favorites.each do |favorite| %>
    <li><%= favorite.member_id %></li>
  <% end %>
</ul>

<p>Party: <%= @results[0]['party'] %></p>


<p><%= link_to "Edit", edit_user_path(@user) %></p>

<a href="/members">View Members of Congress</a>

app/views/welcome/index.html.erb
<%= render 'refills/hero' %>